// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmvkDz9bZP23WTEOjkDWYTaKiXWzMSMzE',
    appId: '1:967731399770:web:8894d079d56011cc851c63',
    messagingSenderId: '967731399770',
    projectId: 'taskmanager-43f49',
    authDomain: 'taskmanager-43f49.firebaseapp.com',
    storageBucket: 'taskmanager-43f49.firebasestorage.app',
    measurementId: 'G-96SXEL6W65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBz2zm3Iewwwy1qSF_By3cnL5DLS_qzzw',
    appId: '1:967731399770:android:86488759b0d8c022851c63',
    messagingSenderId: '967731399770',
    projectId: 'taskmanager-43f49',
    storageBucket: 'taskmanager-43f49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvQjvVrU3IuHcquqq4pBuo9yxcQxXDWEQ',
    appId: '1:967731399770:ios:78b1e9a49fedbdde851c63',
    messagingSenderId: '967731399770',
    projectId: 'taskmanager-43f49',
    storageBucket: 'taskmanager-43f49.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvQjvVrU3IuHcquqq4pBuo9yxcQxXDWEQ',
    appId: '1:967731399770:ios:78b1e9a49fedbdde851c63',
    messagingSenderId: '967731399770',
    projectId: 'taskmanager-43f49',
    storageBucket: 'taskmanager-43f49.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmvkDz9bZP23WTEOjkDWYTaKiXWzMSMzE',
    appId: '1:967731399770:web:b59734b0cffa59e1851c63',
    messagingSenderId: '967731399770',
    projectId: 'taskmanager-43f49',
    authDomain: 'taskmanager-43f49.firebaseapp.com',
    storageBucket: 'taskmanager-43f49.firebasestorage.app',
    measurementId: 'G-3CNK791XBS',
  );
}
